apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: generic-pr-
  name: generic-pipeline-run
spec:
  pipelineRef:
    name: build-pipeline
  resources:
    - name: git-source
      resourceSpec:
        type: git
        params:
          - name: revision
            value: master
          - name: url
            value: http://github.com/wewang58/hello-openshift.git
  params:
    - name: imageUrl
      value: wewang58/tekton-test
    - name: imageTag
      value: latest
  serviceAccountName: tekton-test
